name: deploy-blogpost

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - blogpost/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      # Runs a single command using the runners shell
      - run: cd blogpost && gcloud builds submit --tag us.gcr.io/kubernetes-demo-345511/blogpost #here
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: demo-cluster-1
          location: asia-east1-a
      # Runs a set of commands using the runners shell
      - run: kubectl delete deployment blogpost && kubectl apply -f ./infra/k8s/post.yaml #here
